/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as accountVerifyEmailRouteImport } from './routes/(account)/verify-email'
import { Route as accountConfirmEmailRouteImport } from './routes/(account)/confirm-email'
import { Route as DashboardSavingsIndexRouteImport } from './routes/dashboard/savings/index'
import { Route as DashboardReportIndexRouteImport } from './routes/dashboard/report/index'
import { Route as DashboardRecurringIndexRouteImport } from './routes/dashboard/recurring/index'
import { Route as DashboardExpenseIndexRouteImport } from './routes/dashboard/expense/index'
import { Route as DashboardCategoryIndexRouteImport } from './routes/dashboard/category/index'
import { Route as DashboardAnalysisIndexRouteImport } from './routes/dashboard/analysis/index'
import { Route as accountRegisterIndexRouteImport } from './routes/(account)/register/index'
import { Route as accountLoginIndexRouteImport } from './routes/(account)/login/index'
import { Route as DashboardUserProfileIndexRouteImport } from './routes/dashboard/user/profile/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const accountVerifyEmailRoute = accountVerifyEmailRouteImport.update({
  id: '/(account)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const accountConfirmEmailRoute = accountConfirmEmailRouteImport.update({
  id: '/(account)/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSavingsIndexRoute = DashboardSavingsIndexRouteImport.update({
  id: '/savings/',
  path: '/savings/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReportIndexRoute = DashboardReportIndexRouteImport.update({
  id: '/report/',
  path: '/report/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRecurringIndexRoute = DashboardRecurringIndexRouteImport.update({
  id: '/recurring/',
  path: '/recurring/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardExpenseIndexRoute = DashboardExpenseIndexRouteImport.update({
  id: '/expense/',
  path: '/expense/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCategoryIndexRoute = DashboardCategoryIndexRouteImport.update({
  id: '/category/',
  path: '/category/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAnalysisIndexRoute = DashboardAnalysisIndexRouteImport.update({
  id: '/analysis/',
  path: '/analysis/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const accountRegisterIndexRoute = accountRegisterIndexRouteImport.update({
  id: '/(account)/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const accountLoginIndexRoute = accountLoginIndexRouteImport.update({
  id: '/(account)/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUserProfileIndexRoute =
  DashboardUserProfileIndexRouteImport.update({
    id: '/user/profile/',
    path: '/user/profile/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/confirm-email': typeof accountConfirmEmailRoute
  '/verify-email': typeof accountVerifyEmailRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/login': typeof accountLoginIndexRoute
  '/register': typeof accountRegisterIndexRoute
  '/dashboard/analysis': typeof DashboardAnalysisIndexRoute
  '/dashboard/category': typeof DashboardCategoryIndexRoute
  '/dashboard/expense': typeof DashboardExpenseIndexRoute
  '/dashboard/recurring': typeof DashboardRecurringIndexRoute
  '/dashboard/report': typeof DashboardReportIndexRoute
  '/dashboard/savings': typeof DashboardSavingsIndexRoute
  '/dashboard/user/profile': typeof DashboardUserProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm-email': typeof accountConfirmEmailRoute
  '/verify-email': typeof accountVerifyEmailRoute
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof accountLoginIndexRoute
  '/register': typeof accountRegisterIndexRoute
  '/dashboard/analysis': typeof DashboardAnalysisIndexRoute
  '/dashboard/category': typeof DashboardCategoryIndexRoute
  '/dashboard/expense': typeof DashboardExpenseIndexRoute
  '/dashboard/recurring': typeof DashboardRecurringIndexRoute
  '/dashboard/report': typeof DashboardReportIndexRoute
  '/dashboard/savings': typeof DashboardSavingsIndexRoute
  '/dashboard/user/profile': typeof DashboardUserProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/(account)/confirm-email': typeof accountConfirmEmailRoute
  '/(account)/verify-email': typeof accountVerifyEmailRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/(account)/login/': typeof accountLoginIndexRoute
  '/(account)/register/': typeof accountRegisterIndexRoute
  '/dashboard/analysis/': typeof DashboardAnalysisIndexRoute
  '/dashboard/category/': typeof DashboardCategoryIndexRoute
  '/dashboard/expense/': typeof DashboardExpenseIndexRoute
  '/dashboard/recurring/': typeof DashboardRecurringIndexRoute
  '/dashboard/report/': typeof DashboardReportIndexRoute
  '/dashboard/savings/': typeof DashboardSavingsIndexRoute
  '/dashboard/user/profile/': typeof DashboardUserProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/confirm-email'
    | '/verify-email'
    | '/dashboard/'
    | '/login'
    | '/register'
    | '/dashboard/analysis'
    | '/dashboard/category'
    | '/dashboard/expense'
    | '/dashboard/recurring'
    | '/dashboard/report'
    | '/dashboard/savings'
    | '/dashboard/user/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirm-email'
    | '/verify-email'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/analysis'
    | '/dashboard/category'
    | '/dashboard/expense'
    | '/dashboard/recurring'
    | '/dashboard/report'
    | '/dashboard/savings'
    | '/dashboard/user/profile'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/(account)/confirm-email'
    | '/(account)/verify-email'
    | '/dashboard/'
    | '/(account)/login/'
    | '/(account)/register/'
    | '/dashboard/analysis/'
    | '/dashboard/category/'
    | '/dashboard/expense/'
    | '/dashboard/recurring/'
    | '/dashboard/report/'
    | '/dashboard/savings/'
    | '/dashboard/user/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  accountConfirmEmailRoute: typeof accountConfirmEmailRoute
  accountVerifyEmailRoute: typeof accountVerifyEmailRoute
  accountLoginIndexRoute: typeof accountLoginIndexRoute
  accountRegisterIndexRoute: typeof accountRegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(account)/verify-email': {
      id: '/(account)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof accountVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(account)/confirm-email': {
      id: '/(account)/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof accountConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/savings/': {
      id: '/dashboard/savings/'
      path: '/savings'
      fullPath: '/dashboard/savings'
      preLoaderRoute: typeof DashboardSavingsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/report/': {
      id: '/dashboard/report/'
      path: '/report'
      fullPath: '/dashboard/report'
      preLoaderRoute: typeof DashboardReportIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/recurring/': {
      id: '/dashboard/recurring/'
      path: '/recurring'
      fullPath: '/dashboard/recurring'
      preLoaderRoute: typeof DashboardRecurringIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/expense/': {
      id: '/dashboard/expense/'
      path: '/expense'
      fullPath: '/dashboard/expense'
      preLoaderRoute: typeof DashboardExpenseIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/category/': {
      id: '/dashboard/category/'
      path: '/category'
      fullPath: '/dashboard/category'
      preLoaderRoute: typeof DashboardCategoryIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/analysis/': {
      id: '/dashboard/analysis/'
      path: '/analysis'
      fullPath: '/dashboard/analysis'
      preLoaderRoute: typeof DashboardAnalysisIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(account)/register/': {
      id: '/(account)/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof accountRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(account)/login/': {
      id: '/(account)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof accountLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/user/profile/': {
      id: '/dashboard/user/profile/'
      path: '/user/profile'
      fullPath: '/dashboard/user/profile'
      preLoaderRoute: typeof DashboardUserProfileIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAnalysisIndexRoute: typeof DashboardAnalysisIndexRoute
  DashboardCategoryIndexRoute: typeof DashboardCategoryIndexRoute
  DashboardExpenseIndexRoute: typeof DashboardExpenseIndexRoute
  DashboardRecurringIndexRoute: typeof DashboardRecurringIndexRoute
  DashboardReportIndexRoute: typeof DashboardReportIndexRoute
  DashboardSavingsIndexRoute: typeof DashboardSavingsIndexRoute
  DashboardUserProfileIndexRoute: typeof DashboardUserProfileIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAnalysisIndexRoute: DashboardAnalysisIndexRoute,
  DashboardCategoryIndexRoute: DashboardCategoryIndexRoute,
  DashboardExpenseIndexRoute: DashboardExpenseIndexRoute,
  DashboardRecurringIndexRoute: DashboardRecurringIndexRoute,
  DashboardReportIndexRoute: DashboardReportIndexRoute,
  DashboardSavingsIndexRoute: DashboardSavingsIndexRoute,
  DashboardUserProfileIndexRoute: DashboardUserProfileIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  accountConfirmEmailRoute: accountConfirmEmailRoute,
  accountVerifyEmailRoute: accountVerifyEmailRoute,
  accountLoginIndexRoute: accountLoginIndexRoute,
  accountRegisterIndexRoute: accountRegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
