/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoryIndexRouteImport } from './routes/category/index'
import { Route as AccountRegisterIndexRouteImport } from './routes/account/register/index'
import { Route as AccountLoginIndexRouteImport } from './routes/account/login/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIndexRoute = CategoryIndexRouteImport.update({
  id: '/category/',
  path: '/category/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRegisterIndexRoute = AccountRegisterIndexRouteImport.update({
  id: '/account/register/',
  path: '/account/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLoginIndexRoute = AccountLoginIndexRouteImport.update({
  id: '/account/login/',
  path: '/account/login/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/category': typeof CategoryIndexRoute
  '/account/login': typeof AccountLoginIndexRoute
  '/account/register': typeof AccountRegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/category': typeof CategoryIndexRoute
  '/account/login': typeof AccountLoginIndexRoute
  '/account/register': typeof AccountRegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/category/': typeof CategoryIndexRoute
  '/account/login/': typeof AccountLoginIndexRoute
  '/account/register/': typeof AccountRegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/category' | '/account/login' | '/account/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/category' | '/account/login' | '/account/register'
  id: '__root__' | '/' | '/category/' | '/account/login/' | '/account/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoryIndexRoute: typeof CategoryIndexRoute
  AccountLoginIndexRoute: typeof AccountLoginIndexRoute
  AccountRegisterIndexRoute: typeof AccountRegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/': {
      id: '/category/'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof CategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/register/': {
      id: '/account/register/'
      path: '/account/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/login/': {
      id: '/account/login/'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoryIndexRoute: CategoryIndexRoute,
  AccountLoginIndexRoute: AccountLoginIndexRoute,
  AccountRegisterIndexRoute: AccountRegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
