/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardExpenseIndexRouteImport } from './routes/dashboard/expense/index'
import { Route as DashboardCategoryIndexRouteImport } from './routes/dashboard/category/index'
import { Route as AccountRegisterIndexRouteImport } from './routes/account/register/index'
import { Route as AccountLoginIndexRouteImport } from './routes/account/login/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardExpenseIndexRoute = DashboardExpenseIndexRouteImport.update({
  id: '/expense/',
  path: '/expense/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCategoryIndexRoute = DashboardCategoryIndexRouteImport.update({
  id: '/category/',
  path: '/category/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AccountRegisterIndexRoute = AccountRegisterIndexRouteImport.update({
  id: '/account/register/',
  path: '/account/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLoginIndexRoute = AccountLoginIndexRouteImport.update({
  id: '/account/login/',
  path: '/account/login/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/account/login': typeof AccountLoginIndexRoute
  '/account/register': typeof AccountRegisterIndexRoute
  '/dashboard/category': typeof DashboardCategoryIndexRoute
  '/dashboard/expense': typeof DashboardExpenseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/account/login': typeof AccountLoginIndexRoute
  '/account/register': typeof AccountRegisterIndexRoute
  '/dashboard/category': typeof DashboardCategoryIndexRoute
  '/dashboard/expense': typeof DashboardExpenseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/account/login/': typeof AccountLoginIndexRoute
  '/account/register/': typeof AccountRegisterIndexRoute
  '/dashboard/category/': typeof DashboardCategoryIndexRoute
  '/dashboard/expense/': typeof DashboardExpenseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/account/login'
    | '/account/register'
    | '/dashboard/category'
    | '/dashboard/expense'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/account/login'
    | '/account/register'
    | '/dashboard/category'
    | '/dashboard/expense'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/account/login/'
    | '/account/register/'
    | '/dashboard/category/'
    | '/dashboard/expense/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AccountLoginIndexRoute: typeof AccountLoginIndexRoute
  AccountRegisterIndexRoute: typeof AccountRegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/expense/': {
      id: '/dashboard/expense/'
      path: '/expense'
      fullPath: '/dashboard/expense'
      preLoaderRoute: typeof DashboardExpenseIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/category/': {
      id: '/dashboard/category/'
      path: '/category'
      fullPath: '/dashboard/category'
      preLoaderRoute: typeof DashboardCategoryIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/account/register/': {
      id: '/account/register/'
      path: '/account/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/login/': {
      id: '/account/login/'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCategoryIndexRoute: typeof DashboardCategoryIndexRoute
  DashboardExpenseIndexRoute: typeof DashboardExpenseIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCategoryIndexRoute: DashboardCategoryIndexRoute,
  DashboardExpenseIndexRoute: DashboardExpenseIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AccountLoginIndexRoute: AccountLoginIndexRoute,
  AccountRegisterIndexRoute: AccountRegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
